builds:
  # add here as well if you ever change this https://github.com/Bloodmallet/bloodytools/blob/master/bloodytools/simulations/talent_tree_paths/priest_shadow.yaml
  st-test: #idk if it's a good thing to have the same build, but just want to check the value for 1 build
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkDAAAAAAAAAAAAAIhWEJSJikEJJJCSjkkEpRgICpUiQCUgE # DA_yshaarj_cthun_81144371214255_Spike_DR
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkDAAAAAAAAAAAAAIhWEJSJikEJJJCSjkkEpRgICpUiQCUgE # DA_yshaarj_cthun_81144371214255_Spike_DR
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkDAAAAAAAAAAAAAIhWEJSJikEJJJCSjkkEpRgICpUiQCUgE # DA_yshaarj_cthun_81144371214255_Spike_DR
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkDAAAAAAAAAAAAAIhWEJSJikEJJJCSjkkEpRgICpUiQCUgE # DA_yshaarj_cthun_81144371214255_Spike_DR
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkDAAAAAAAAAAAAAIhWEJSJikEJJJCSjkkEpRgICpUiQCUgE # DA_yshaarj_cthun_81144371214255_Spike_DR
  yogg-cthun:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAgkEJBAAAAAAAAAAAAIkGRi0CSSSkDkIINSSSkGBJIki0CJBQSA # VF_yogg_cthun_119201344746415_Spike_DR_TS
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAESiIBAAAAAAAAAAAAIoJRSSDSSSSkIINSSSkGBJIki0CJBQSA # VF_nzoth_yogg_cthun_129962385069999_Spike_DR_TS
    single: BIQAAAAAAAAAAAAAAAAAAAAAAgkEJBAAAAAAAAAAAAIkGRi0CSSSkDkIINSSSkGBJIki0CJBQSA # VF_yogg_cthun_119201344746415_Spike_DR_TS
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAgkQSAAAAAAAAAAAAACp5ARSSLIJJRkIINSSSkGBJIki0CJBQSA # VF_yogg_cthun_119242146935727_Spike_DR_TS
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAESiIBAAAAAAAAAAAAIoJRSSDSSSSkIINSSSkGBJIki0CJBQSA # VF_nzoth_yogg_cthun_129962385069999_Spike_DR_TS
  yshaarj-cthun:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIkE5ABAAAAAAAAAAAAIJaRkIlgkERSig0IJJRaEkgQKSLkEASA # DA_yshaarj_cthun_81144613401519_Spike_DR
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkcAAAAAAAAAAAAAgEaRkIlgkEJJJCSjkkEpRQCCpItQSAIB # DA_yshaarj_cthun_81144444614575_Spike_DR
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIQSEAAAAAAAAAAAAgEpERiUiIJRSSigUIJJRaEIiQKSLkEUgA # DA_yshaarj_cthun_81144643565487_Flay
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIkkEBAAAAAAAAAAAAIhWEJShIJRSSig0IJJRaEkgQKSLkEASA # DA_yshaarj_cthun_81144643835823_Spike_DR
    3t: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkEAAAAAAAAAAAAgEaRkIFIJRSSig0IJJRaEkgQKSLkEASA # DA_yshaarj_cthun_81144713041839_Spike_DR
  da-yshaarj-nzoth-cthun:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAkAJCAAAAAAAAAAAAgEpFRSSJikEJJJCShkkEpRgICpItQSQBC # DA_yshaarj_nzoth_cthun_89674310203311_Flay_DR
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAkQSiDAAAAAAAAAAAAAIhWEJJlISSkkkIINSSSkGBJIki0CJBgE # DA_yshaarj_nzoth_cthun_89674176264111_Spike_DR
    single: BIQAAAAAAAAAAAAAAAAAAAAAAkAJEAAAAAAAAAAAAgEpERSSJikEJJJCShkkEpRgICpItQSQBC # DA_yshaarj_nzoth_cthun_89674448615343_Flay
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAkAJEAAAAAAAAAAAAgEpFRSSJikEJJJCShkkEpRgICpItQSQBC # DA_yshaarj_nzoth_cthun_89674448615343_Flay_DR
    3t: BIQAAAAAAAAAAAAAAAAAAAAAAkQSCBAAAAAAAAAAAAIJaJRSSBSSkEJCSjkkEpRQCCpItQSAIB # DA_yshaarj_nzoth_cthun_90808285648815_Spike_DR
  vf-yshaarj:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIIJJBAAAAAAAAAAAAIhWEJSDSSkkkIIFSSSkGBiIki0CJBFIB # VF_yshaarj_cthun_81144713041839_Spike_DR
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAkQk4AAAAAAAAAAAAAASSaJRSSjIJRSkIINSSSkGBJIki0CJBgA # VF_yshaarj_nzoth_cthun_90808081946543_Flay_DR
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIQSEAAAAAAAAAAAAgEpERi0iIJRSSigUIJJRaEIiQKSLkEUgA # VF_yshaarj_cthun_81144643565487_Flay
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIEJRAAAAAAAAAAAAASkWEJSLikEJJJCSjkkEpRQCCpItQSAIA # VF_yshaarj_cthun_81144643565487_Flay_DR
    3t: BIQAAAAAAAAAAAAAAAAAAAAAAkQk4AAAAAAAAAAAAAASSaJRSSjIJRSkIINSSSkGBJIki0CJBgA # VF_yshaarj_nzoth_cthun_90808081946543_Flay_DR
gear:
  head: "crest_of_lunar_communion,id=207281,ilevel=489" # mastery/crit
  neck: "eye_of_the_rising_flame,id=207163,ilevel=489,gem_id=192985/192948/192948,bonus_id=8782" # mastery/haste
  shoulders: "shoulderguardians_of_lunar_communion,id=207279,ilevel=489" # crit/mastery
  back: "undulating_sporecloak,id=205025,ilevel=483,enchant_id=6592" # versa/mastery
  chest: "cassock_of_lunar_communion,id=207284,ilevel=489,enchant_id=6625" # mastery/versa
  wrists: "arathi_field_bandages,id=207867,ilevel=489,enchant_id=6574" # crit/mastery
  hands: "touch_of_lunar_communion,id=207282,ilevel=489" # haste/crit
  waist: "vibrant_wildercloth_girdle,id=193516,ilevel=483,enchant_id=6904,bonus_id=9379/8960,crafted_stats=36/49" # mastery=haste
  legs: "leggings_of_lunar_communion,id=207280,ilevel=489,enchant_id=6541" # haste/mastery
  feet: "poulaines_of_lunar_communion,id=207283,ilevel=489,enchant_id=6607" # mastery/crit
  finger1: "band_of_burning_thorns,id=207159,ilevel=489,enchant_id=6556" # haste/mastery
  finger2: "signet_of_titanic_insight,id=192999,ilevel=489,enchant_id=6554,crafted_stats=36/49" # haste=mastery
  trinket1: "nymues_unraveling_spindle,id=208615,ilevel=489"
  trinket2: "pips_emerald_friendship_badge,id=207168,ilevel=489"
  main_hand: "vakash_the_shadowed_inferno,id=207788,ilevel=489,enchant_id=6643" # mastery/haste
  off_hand: "tricksters_captivating_chime,id=207796,ilevel=489" # mastery/haste
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character. Lists each consumable at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only."
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims Food and Augment Rune consumables you can use to augment your character."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot. Lists each enchant at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - enchants.simc
  gems:
    description: "Sims all available gems against each other. Lists each gem at ranks 1, 2, and 3."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - gems.simc
  racials:
    description: "Swaps out the racial that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  special-gear:
    description: "Sims unique gear with effects to see the DPS gain. Includes Tailoring, Jewelcrafting, and Inscription gear, crafted with BiS stats when possible. Compared against Mythic BiS gear from the Raid or Mythic+ gear.<br><br>A negative DPS gain means the crafted piece with BiS stats is worse than the Mythic BiS piece. This usually means the BiS piece has a higher ilvl than the crafted piece."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - gear.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 100 stat each step)."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims various talent builds generated by Talent Tree Manager. Shows the major cooldown and Idol combination used for that actor, names in gold can be clicked to copy the import string."
    iterations: smart
    builds: false
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - DA-Spike.simc
      - DA-Flay.simc
      - DA-Spike_DR.simc
      - DA-Flay_DR.simc
      - VF-Spike.simc
      - VF-Flay.simc
      - VF-Spike_DR.simc
      - VF-Flay_DR.simc
  talents-top:
    description: "Shows top talents."
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - talents.simc
  tiersets:
    description: "Sims each tier set currently available by just activating just the set effect, not with the gear."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: Combines the top trinkets together to get your BiS 2 trinkets.
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 441
      - 447
      - 450
      - 454
      - 457
      - 460
      - 463
      - 467
      - 470
      - 473
      - 476
      - 480
      - 483
      - 486
      - 489
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for current BiS gear setup..
    builds: true
    weights: true
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsAmirdrassilTheDreamsHope
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
threeTargetWeights: weightsThreeTargets
fourTargetWeights: weightsFourTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
dungeonSeason: 2
dungeonStandardWeights: weightsStandardSeasonTwo
dungeonPushWeights: weightsPushSeasonTwo
simcBuild: latest
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 100
  retryInterval: 10
analyze:
  dungeonCharts: false
  markdown: true
  csv: true
  json: true
stats:
  base: 2000
  steps: 500
  total: 16000
  min:
    haste: 5000
    mastery: 5000
  include:
    - mastery
    - haste
    - crit
    - versatility
