builds:
  # add here as well if you ever change this https://github.com/Bloodmallet/bloodytools/blob/master/bloodytools/simulations/talent_tree_paths/priest_shadow.yaml
  yogg-cthun:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAgkEJBAAAAAAAAAAAAIkGRi0CSSSkDkIINSSSkGBJIki0CJBQSA # VF_yogg_cthun_119201344746415_Spike_DR_TS
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAESiIBAAAAAAAAAAAAIoJRSSDSSSSkIINSSSkGBJIki0CJBQSA # VF_nzoth_yogg_cthun_129962385069999_Spike_DR_TS
    single: BIQAAAAAAAAAAAAAAAAAAAAAAgkEJBAAAAAAAAAAAAIkGRi0CSSSkDkIINSSSkGBJIki0CJBQSA # VF_yogg_cthun_119201344746415_Spike_DR_TS
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAgkQSAAAAAAAAAAAAACp5ARSSLIJJRkIINSSSkGBJIki0CJBQSA # VF_yogg_cthun_119242146935727_Spike_DR_TS
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAESiIBAAAAAAAAAAAAIoJRSSDSSSSkIINSSSkGBJIki0CJBQSA # VF_nzoth_yogg_cthun_129962385069999_Spike_DR_TS
  yshaarj-cthun:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIkE5ABAAAAAAAAAAAAIJaRkIlgkERSig0IJJRaEkgQKSLkEASA # DA_yshaarj_cthun_81144613401519_Spike_DR
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkcAAAAAAAAAAAAAgEaRkIlgkEJJJCSjkkEpRQCCpItQSAIB # DA_yshaarj_cthun_81144444614575_Spike_DR
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIkE5ABAAAAAAAAAAAAIJaRkIlgkERSig0IJJRaEkgQKSLkEASA # DA_yshaarj_cthun_81144613401519_Spike_DR
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkEAAAAAAAAAAAAgEaRkIFIJRSSig0IJJRaEkgQKSLkEASA # DA_yshaarj_cthun_81144713041839_Spike_DR
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAIkkkEAAAAAAAAAAAAgEaRkIFIJRSSig0IJJRaEkgQKSLkEASA # DA_yshaarj_cthun_81144713041839_Spike_DR
  nzoth-cthun:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAEkEJBAAAAAAAAAAAAIoRkkUiDIJJRSig0IJJRaEkgQKSLkEASA # DA_nzoth_cthun_98181776634799_Spike_DR
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAkQikcAAAAAAAAAAAAAgEaRkIlgkEJJJCSjkkEpRQCCpItQSAIB # DA_yshaarj_nzoth_cthun_98734483175343_Spike_DR
    single: BIQAAAAAAAAAAAAAAAAAAAAAAEkEJBAAAAAAAAAAAAIoRkkUiDIJJRSig0IJJRaEkgQKSLkEASA # DA_nzoth_cthun_98181776634799_Spike_DR
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAEkEJBAAAAAAAAAAAAIkGRSSJIJJRSig0IJJRaEkgQKSLkEASA # DA_nzoth_cthun_98181774799791_Spike_DR
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAkQISAAAAAAAAAAAAASOQaJRSSDSSSSkIINSSSkGBJIki0CJBgA # VF_yshaarj_nzoth_cthun_90810537711535_Flay_DR
gear:
  head: "tier,id=207281,ilevel=489" # mastery/crit
  neck: "neck,id=207163,ilevel=489" # mastery/haste
  shoulders: "tier,id=207279,ilevel=489" # crit/mastery
  back: "back,id=207161,ilevel=489" # mastery/crit
  chest: "chest,id=207121,ilevel=489" # haste/crit
  wrists: "wrists,id=210204,ilevel=489" # mastery/haste
  hands: "tier,id=207282,ilevel=489" # haste/crit
  waist: "waist,id=207124,ilevel=489" # haste/mastery
  legs: "tier,id=207280,ilevel=489" # haste/mastery
  feet: "feet,id=207123,ilevel=489" # mastery/haste
  finger1: "ring1,id=207159,ilevel=489" # haste/mastery
  finger2: "archdruids_tainted_seal,id=134487,ilevel=489" # mastery/haste
  trinket1: "spoils_of_neltharus,id=193773,ilevel=447"
  trinket2: "ominous_chromatic_essence,id=203729,ilevel=444"
  main_hand: "staff,id=207795,ilevel=489" # haste/mastery
  off_hand: ""
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character. Lists each consumable at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only."
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims Food and Augment Rune consumables you can use to augment your character."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot. Lists each enchant at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - enchants.simc
  gems:
    description: "Sims all available gems against each other. Lists each gem at ranks 1, 2, and 3."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - gems.simc
  racials:
    description: "Swaps out the racial that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  special-gear:
    description: "Sims unique gear with effects to see the DPS gain. Includes Tailoring, Jewelcrafting, and Inscription gear, crafted with BiS stats when possible. Compared against Mythic BiS gear from the Raid or Mythic+ gear.<br><br>A negative DPS gain means the crafted piece with BiS stats is worse than the Mythic BiS piece. This usually means the BiS piece has a higher ilvl than the crafted piece."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - gear.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 100 stat each step)."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims various talent builds generated by Talent Tree Manager. Shows the major cooldown and Idol combination used for that actor, names in gold can be clicked to copy the import string."
    iterations: smart
    builds: false
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - DA-Spike.simc
      - DA-Flay.simc
      - DA-Spike_DR.simc
      - DA-Flay_DR.simc
      - DA-Spike_TS.simc
      - DA-Flay_TS.simc
      - DA-Spike_DR_TS.simc
      - DA-Flay_DR_TS.simc
      - VF-Spike.simc
      - VF-Flay.simc
      - VF-Spike_DR.simc
      - VF-Flay_DR.simc
      - VF-Spike_TS.simc
      - VF-Flay_TS.simc
      - VF-Spike_DR_TS.simc
      - VF-Flay_DR_TS.simc
  talents-top:
    description: "Shows top talents."
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - talents.simc
  tiersets:
    description: "Sims each tier set currently available by just activating just the set effect, not with the gear."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: Combines the top trinkets together to get your BiS 2 trinkets.
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 411
      - 415
      - 418
      - 421
      - 424
      - 428
      - 431
      - 434
      - 437
      - 441
      - 444
      - 447
      - 450
      - 457
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for current BiS gear setup..
    builds: true
    weights: true
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsAberrusTheShadowedCrucible
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
fourTargetWeights: weightsFourTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
dungeonSeason: 2
dungeonStandardWeights: weightsStandardSeasonTwo
dungeonPushWeights: weightsPushSeasonTwo
simcBuild: latest
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 100
  retryInterval: 10
analyze:
  dungeonCharts: false
  markdown: true
  csv: true
  json: true
stats:
  base: 1600
  steps: 1000
  total: 12600
  include:
    - mastery
    - haste
    - crit
    - versatility
